---
- hosts: 54.242.94.177
  become: yes
  vars:
    build_number: '{{ BUILD_NUMBER }}'
  tasks:
      
    - name: login to jfrog
      shell: docker login -u pratikshasinghshs@gmail.com -p Pratiksha@shs1 pratikshahost.jfrog.io/
  
    
    - name: pull an image
      shell: docker pull pratikshahost.jfrog.io/docker-trial/appa:{{ BUILD_NUMBER }}

    - name: remove container
      shell: docker rm -f devopsAppDeploy
        
    - name: create a application container
      shell: docker run -id --name devopsAppDeploy -p 8111:8080 pratikshahost.jfrog.io/docker-trial/appa:{{ BUILD_NUMBER }}
 
   
